/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/**/*.{html,ts}',
  ],
  theme: {
    extend: {
      colors: {
        // DXC Brand Colors
        'dxc-midnight':   '#0E1020',
        'dxc-royal':      '#004AAC',
        'dxc-blue':       '#4995FF',
        'dxc-sky':        '#A1E6FF',
        'dxc-canvas':     '#F6F3F0',
        'dxc-peach':      '#FFC982',
        'dxc-gold':       '#FFAE41',
        'dxc-melon':      '#FF7E51',
        'dxc-red':        '#D14600',

        // Stitch Material Design token aliases (matches generated HTML)
        'primary':                    '#b0c6ff',
        'primary-container':          '#004aac',
        'on-primary':                 '#002d6e',
        'on-primary-container':       '#a8c1ff',
        'primary-fixed':              '#d9e2ff',
        'primary-fixed-dim':          '#b0c6ff',
        'on-primary-fixed':           '#001945',
        'on-primary-fixed-variant':   '#00429b',
        'secondary':                  '#a9c7ff',
        'secondary-container':        '#016ed6',
        'on-secondary':               '#003063',
        'on-secondary-container':     '#f1f4ff',
        'secondary-fixed':            '#d6e3ff',
        'secondary-fixed-dim':        '#a9c7ff',
        'on-secondary-fixed':         '#001b3d',
        'on-secondary-fixed-variant': '#00468c',
        'tertiary':                   '#8cd0e9',
        'tertiary-container':         '#00576b',
        'on-tertiary':                '#003543',
        'on-tertiary-container':      '#87cbe4',
        'tertiary-fixed':             '#b5ebff',
        'tertiary-fixed-dim':         '#8cd0e9',
        'on-tertiary-fixed':          '#001f28',
        'on-tertiary-fixed-variant':  '#004e60',
        'error':                      '#ffb4ab',
        'error-container':            '#93000a',
        'on-error':                   '#690005',
        'on-error-container':         '#ffdad6',
        'background':                 '#101222',
        'on-background':              '#e1e1f8',
        'surface':                    '#101222',
        'surface-dim':                '#101222',
        'surface-bright':             '#36384a',
        'surface-tint':               '#b0c6ff',
        'surface-variant':            '#323445',
        'on-surface':                 '#e1e1f8',
        'on-surface-variant':         '#c3c6d5',
        'surface-container-lowest':   '#0b0d1d',
        'surface-container-low':      '#181a2b',
        'surface-container':          '#1c1e2f',
        'surface-container-high':     '#27293a',
        'surface-container-highest':  '#323445',
        'outline':                    '#8d909e',
        'outline-variant':            '#434652',
        'inverse-surface':            '#e1e1f8',
        'inverse-on-surface':         '#2d2f41',
        'inverse-primary':            '#225abc',
        // Semantic aliases used in dashboard/components
        'warning':                    '#FFAE41',
        'success':                    '#4caf50',
      },
      borderRadius: {
        DEFAULT:  '0.125rem',
        lg:       '0.25rem',
        xl:       '0.5rem',
        full:     '0.75rem',
        pill:     '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body:     ['Public Sans', 'sans-serif'],
        label:    ['Public Sans', 'sans-serif'],
        sora:     ['Sora', 'sans-serif'],
        plex:     ['IBM Plex Sans', 'sans-serif'],
        mono:     ['IBM Plex Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
