pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                echo 'Construction du projet...'
            }
        }

        stage('Test') {
            steps {
                echo 'Execution des tests...'
            }
        }

        stage('Docker Build') {
            steps {
                echo 'Construction des images Docker...'
                echo 'Frontend image build'
                echo 'Backend image build'
                echo 'AI service image build'
            }
        }

        stage('Report') {
            steps {
                echo 'Generation du rapport...'
            }
        }

    }

    post {
        success {
            echo 'Pipeline execute avec succes.'
        }
        failure {
            echo 'Le pipeline a echoue.'
        }
    }
}